apiVersion: v1
kind: Template
labels:
  template: fedora-builder
metadata:
  annotations:
    description: fedora container
    iconClass: fedora
    tags: instant-app
  name: fedora-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
    name: fedora
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: fedora
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: fedora:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        noCache: true
        env:
          - name: CONTAINER_NAME
            value: fedora
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/samvarankashyap/ci-pipeline-dummies
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: config/Dockerfiles/fedora
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: master
